apiVersion: v1
kind: Namespace
metadata:
  name: rpc
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc
  namespace: rpc
  labels:
    app: rpc
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: rpc
  template:
    metadata:
      labels:
        app: rpc
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            EXIT_ON_ZERO_ACTIVE_CONNECTIONS: 'true'
    spec:
      containers:
        - name: rpc
          image: rpc
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rpc-svc
  namespace: rpc
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: rpc

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rpc-virtual-svc
  namespace: rpc
spec:
  hosts:
    - rpc-svc.rpc.svc.cluster.local
  http:
    - route:
        - destination:
            host: rpc-svc.rpc.svc.cluster.local
            port:
              number: 8080
      timeout: 8s
      match:
        - port: 8080
      retries:
        attempts: 3
        perTryTimeout: 2s
        # ref: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-grpc-on
        retryOn: unavailable,deadline-exceeded,reset,connect-failure