# doc: https://skaffold.dev/docs/references/yaml
apiVersion: skaffold/v2beta29
kind: Config


build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: api
      context: ./helloworld
      docker:
        dockerfile: api/Dockerfile
    - image: rpc
      context: ./helloworld
      docker:
        dockerfile: rpc/Dockerfile

deploy:
  kubectl:
    manifests:
    - istio/mesh_default.yaml
    - helloworld/api/k8s/*
    - helloworld/rpc/k8s/*

portForward:
  - resourceType: service
    resourceName: locust
    namespace: locust
    port: 8089
    localPort: 8089