// Code generated by goctl. DO NOT EDIT!
// Source: helloworld.proto

package server

import (
	"context"

	"helloworld/rpc/helloworld"
	"helloworld/rpc/internal/logic"
	"helloworld/rpc/internal/svc"
)

type GreeterServer struct {
	svcCtx *svc.ServiceContext
	helloworld.UnimplementedGreeterServer
}

func NewGreeterServer(svcCtx *svc.ServiceContext) *GreeterServer {
	return &GreeterServer{
		svcCtx: svcCtx,
	}
}

func (s *GreeterServer) SayHello(ctx context.Context, in *helloworld.HelloRequest) (*helloworld.HelloReply, error) {
	l := logic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}
