// Code generated by goctl. DO NOT EDIT!
// Source: helloworld.proto

package server

import (
	"context"

	"helloworld/rpc/helloworld"
	"helloworld/rpc/internal/logic"
	"helloworld/rpc/internal/svc"
)

type HelloworldServer struct {
	svcCtx *svc.ServiceContext
	helloworld.UnimplementedHelloworldServer
}

func NewHelloworldServer(svcCtx *svc.ServiceContext) *HelloworldServer {
	return &HelloworldServer{
		svcCtx: svcCtx,
	}
}

func (s *HelloworldServer) Call(ctx context.Context, in *helloworld.Request) (*helloworld.Response, error) {
	l := logic.NewCallLogic(ctx, s.svcCtx)
	return l.Call(in)
}
