// Code generated by goctl. DO NOT EDIT!
// Source: helloworld.proto

package server

import (
	"context"

	"helloworld/rpc/helloworld"
	"helloworld/rpc/internal/logic"
	"helloworld/rpc/internal/svc"
)

type HelloWorldServer struct {
	svcCtx *svc.ServiceContext
	helloworld.UnimplementedHelloWorldServer
}

func NewHelloWorldServer(svcCtx *svc.ServiceContext) *HelloWorldServer {
	return &HelloWorldServer{
		svcCtx: svcCtx,
	}
}

func (s *HelloWorldServer) Call(ctx context.Context, in *helloworld.Request) (*helloworld.Response, error) {
	l := logic.NewCallLogic(ctx, s.svcCtx)
	return l.Call(in)
}
