// Code generated by goctl. DO NOT EDIT!
// Source: helloworld.proto

package greeter

import (
	"context"

	"helloworld/rpc/helloworld"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	HelloReply   = helloworld.HelloReply
	HelloRequest = helloworld.HelloRequest

	Greeter interface {
		SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	}

	defaultGreeter struct {
		cli zrpc.Client
	}
)

func NewGreeter(cli zrpc.Client) Greeter {
	return &defaultGreeter{
		cli: cli,
	}
}

func (m *defaultGreeter) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	client := helloworld.NewGreeterClient(m.cli.Conn())
	return client.SayHello(ctx, in, opts...)
}
