apiVersion: v1
kind: Namespace
metadata:
  name: api
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
  labels:
    app: api
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            EXIT_ON_ZERO_ACTIVE_CONNECTIONS: 'true'
    spec:
      containers:
      - name: api
        image: api
        ports:
        - containerPort: 8888
        env:
          - name: RPC_ENDPOINT
            value: rpc-svc.rpc.svc.cluster.local:8080
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi

---

apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: api
spec:
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: api
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rpc-virtual-svc
  namespace: api
spec:
  hosts:
    - rpc-svc.rpc.svc.cluster.local
  http:
    - route:
        - destination:
            host: rpc-svc.rpc.svc.cluster.local
            port:
              number: 8080
      timeout: 10s
      match:
        - port: 8080
      retries:
        attempts: 3
        perTryTimeout: 8s
        # ref: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-grpc-on
        retryOn: unavailable,deadline-exceeded,reset,connect-failure