// Code generated by goctl. DO NOT EDIT!
// Source: helloworld.proto

package helloworldclient

import (
	"context"

	"helloworld/rpc/helloworld"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = helloworld.Request
	Response = helloworld.Response

	HelloWorld interface {
		Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultHelloWorld struct {
		cli zrpc.Client
	}
)

func NewHelloWorld(cli zrpc.Client) HelloWorld {
	return &defaultHelloWorld{
		cli: cli,
	}
}

func (m *defaultHelloWorld) Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := helloworld.NewHelloWorldClient(m.cli.Conn())
	return client.Call(ctx, in, opts...)
}
